### ISSUE TITLE
Using with axios

### ISSUE THREAD

**Issue by jlugao** [Deveodk/vue-error-tracker#4]
Hey,
how do I get this to work with axios?

In my main.js I have:
``` javascript
  1 import axios from 'axios'
  2 import config from '../config'
  3 Vue.prototype.axios = axios.create({
  4     baseURL: config.serverURI,
  5 })
  6
  7 Raven
  8     .config('https://[censored]@sentry.io/[censored]')
  9     .addPlugin(RavenVue, Vue)
 10     .install();
 11 Vue.prototype.$raven = Raven
 12
 13 import vueErrorTracker from '@deveodk/vue-error-tracker'
 14 Vue.use(vueErrorTracker)
 15
 16 import errorTracker from '@deveodk/vue-error-tracker'
 17 Vue.use(errorTracker, {
 18     HttpDriver: require('@deveodk/vue-error-tracker/drivers/http/axios.js'),
 19     NotificationDriver: require('@deveodk/vue-error-tracker/drivers/notification/deveoToastr.js'),
 20     ReportDriver: require('@deveodk/vue-error-tracker/drivers/report/sentry.js'),
 21     HttpErrorCodes: {
 22         400: {
 23             title: 'Unknown error',
 24             message: 'Something went wrong',
 25             type: 'error'
 26         },
 27         500: {
 28             title: 'Server error',
 29             message: 'Ooops, server error',
 30             type: 'error'
 31         },
 32         502: {
 33             title: 'server unavailable',
 34             message: 'something is wrong',
 35             type: 'error'
 36         }
 37     }
 38 })
```

but no error is being reported. Could you elaborate on how to use this with axios?

**Comment by jasonkellydk** [comment]
There are two possible problems here. Either you an axios interceptor without the error function ```return Promise.reject(error);```, or the axios instance is not instantiated correctly. 

Personally i use ```vue-axios``` (https://github.com/imcvampire/vue-axios) package. 

But the process of creating the axios prototype is fairly simple. Let me know if that did not solve your problem

**Comment by jlugao** [comment]
hey @jasonkellydk I started using vue-axios and now it works, thanks.
can I ask you a couple more questions?
in sentry, on the additional data pane i get weirdly formatted data:
0 | <
-- | --
190 | a
191 | d
192 | d
193 | i
194 | n
195 | g
...

And I'd like to know if there is a way to pass more arguments?  I would like to log the request, the server response (if any) and the error. And if possible the user and their current role ( I know that this would be specific to my implementation)

Regards,

**Comment by jasonkellydk** [comment]
Can you give an example error response from your server? Perhaps the driver expects a different formatted error response?
